language: python
python:
    - '2.7'

services:
  - docker

env:
  global:
    - VERSION=0.1
    - REPO=synst/bridge

before_script:
  - echo "$DOCKER_PASS" | docker login -u $DOCKER_USER --password-stdin

script:
  - ./build.sh

after_script:
  - docker tag synst/bridge $REPO:latest
  - docker tag synst/bridge $REPO:$VERSION
  - docker tag synst/bridge $REPO:$VERSION.$TRAVIS_BUILD_NUMBER
  - echo "$DOCKER_PASS" | docker login -u $DOCKER_USER --password-stdin
  - docker push $REPO
  - docker push $REPO:$VERSION
  - docker push $REPO:$VERSION.$TRAVIS_BUILD_NUMBER
