version: "3"
services:
  bridge:
    image: synst/bridge:latest
    container_name: bridge
    hostname: bridge
    restart: always
    logging:
      options:
        max-file: "3"
        max-size: "50m"
    environment:
      - NAME=s1
      - TIMEZONE=Europe/Moscow
      - INFLUX_HOST=
      - INFLUX_TOKEN=
      - INFLUX_BUCKET=
      - INFLUX_ORG=
      - INFLUX_TIMEOUT=
      - MQTT_HOST=
      - MQTT_USER=
      - MQTT_PASS=
      - MQTT_SSL=TRUE
      - MQTT_ONLINE_TOPIC=$$bridge/{name}/availability
      - MQTT_ONLINE_CONTENT=online
      - MQTT_WILL_TOPIC=$$bridge/{name}/availability
      - MQTT_WILL_CONTENT=offline
      - MQTT_WILL_QOS=1
      - MQTT_WILL_RETAIN=TRUE
      - REDIS_ENABLE=
      - REDIS_HOST=
      - REDIS_PORT=
      - REDIS_USER=
      - REDIS_PASS=
      - REDIS_TTL=
    # volumes:
    #   - "./console/console.php:/opt/console/console.php"
    #   - "./console/bridge.php:/opt/console/bridge.php"
    #   - "./console/.env:/opt/console/.env"
